steps:
  - name: build
    image: alvrme/alpine-android:android-34-jdk17
    commands:
      - ./gradlew :app:assembleDebug
    event: [pull_request, push, tag]
  - name: publish
    image: curlimages/curl
    commands: 'curl --user qwerty287:$CODEBERG_TOKEN --upload-file app/build/outputs/apk/debug/app-debug.apk "https://codeberg.org/api/packages/qwerty287/generic/ftpclient_debug/$CI_COMMIT_SHA/debug.apk"'
    secrets: [ CODEBERG_TOKEN ]
    when:
      event: push
